### ISSUE TITLE
Implement all Payment features

### ISSUE THREAD

**Issue by Parables** [Parables/arkesel-sdk#3]
## TODO
- [ ] Add Tests
- [ ] Implement Payment class
- [ ] Add Payment facade
- [ ] Add `arkeselPay()` helper
